Repository ChuSon9898/nalssiya, pull requests merged in 2024-01, with the labels that each got.

#4 Design: Favorite UI 화면
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/weather_app/FavoriteActivity.kt
  app/src/main/java/com/example/weather_app/FavoriteListAdapter.kt
  app/src/main/java/com/example/weather_app/FavoriteModel.kt
  app/src/main/java/com/example/weather_app/FavoriteViewModel.kt
  app/src/main/java/com/example/weather_app/MainActivity.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/shape_favorite_search.xml
  app/src/main/res/layout/favorite_activity.xml
  app/src/main/res/layout/favorite_rv_item.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design

#5 Design/home
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/weather_app/MainActivity.kt
  app/src/main/java/com/example/weather_app/data/model/DailyDataModel.kt
  app/src/main/java/com/example/weather_app/data/model/HourlyDataModel.kt
  app/src/main/java/com/example/weather_app/ui/home/DailyListAdapter.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeActivity.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/weather_app/ui/home/HourlyListAdapter.kt
  app/src/main/res/drawable/ic_cloud.png
  app/src/main/res/drawable/ic_moon.png
  app/src/main/res/drawable/ic_rain.png
  app/src/main/res/drawable/ic_snow.png
  app/src/main/res/drawable/ic_sun.png
  app/src/main/res/drawable/ic_sun_and_cloud.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/daily_item.xml
  app/src/main/res/layout/home_activity.xml
  app/src/main/res/layout/hourly_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🛠 Feat

#8 FEAT : Room과 ViewModel 연결, Room 삽입/삭제 기능 확인
  app/build.gradle.kts
  app/src/main/java/com/example/weather_app/data/room/BookmarkDAO.kt
  app/src/main/java/com/example/weather_app/data/room/BookmarkDatabase.kt
  app/src/main/java/com/example/weather_app/data/room/BookmarkEntity.kt
  app/src/main/java/com/example/weather_app/data/room/Repository.kt
  app/src/main/java/com/example/weather_app/data/room/TempClass.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkActivity.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkListAdapter.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkViewModel.kt
  app/src/main/res/layout/bookmark_activity.xml
  app/src/main/res/layout/bookmark_rv_item.xml
Labels: 🛠 Feat

#9 시간별 일기예보API 데이터 불러오기 추가
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/weather_app/data/model/HourlyDataModel.kt
  app/src/main/java/com/example/weather_app/data/retrofit/HourlyInterface.kt
  app/src/main/java/com/example/weather_app/data/retrofit/HourlyRepository.kt
  app/src/main/java/com/example/weather_app/data/retrofit/HourlyWeatherClient.kt
  app/src/main/java/com/example/weather_app/data/retrofit/TempClass.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeActivity.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeViewModelFactory.kt
  app/src/main/java/com/example/weather_app/ui/home/HourlyListAdapter.kt
  app/src/main/java/com/example/weather_app/util/RequestPermissionsUtil.kt
  app/src/main/res/drawable/ic_moon.png
  app/src/main/res/drawable/ic_moon_and_cloud.png
  app/src/main/res/layout/home_activity.xml
  app/src/main/res/layout/home_hourly_item.xml
  app/src/main/res/values/strings.xml
Labels: 📬 API, 🛠 Feat

#14 Feature/daily weather api
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/weather_app/data/model/DailyDataModel.kt
  app/src/main/java/com/example/weather_app/data/model/HourlyDataModel.kt
  app/src/main/java/com/example/weather_app/data/retrofit/DailyTempRepository.kt
  app/src/main/java/com/example/weather_app/data/retrofit/DailyWeatherRepository.kt
  app/src/main/java/com/example/weather_app/data/retrofit/HourlyInterface.kt
  app/src/main/java/com/example/weather_app/data/retrofit/HourlyRepository.kt
  app/src/main/java/com/example/weather_app/data/retrofit/RetrofitClient.kt
  app/src/main/java/com/example/weather_app/data/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkActivity.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkDetailActivity.kt
  app/src/main/java/com/example/weather_app/ui/home/DailyListAdapter.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeActivity.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeViewModelFactory.kt
  app/src/main/java/com/example/weather_app/ui/home/HourlyListAdapter.kt
  app/src/main/res/drawable/ic_list.xml
  app/src/main/res/layout/home_activity.xml
  app/src/main/res/layout/home_daily_item.xml
  app/src/main/res/values/strings.xml
Labels: 📬 API, 🛠 Feat

#16 FEAT : Room 데이터 찾은 후 중복 없으면 추가
  app/src/main/java/com/example/weather_app/data/model/BookmarkDataModel.kt
  app/src/main/java/com/example/weather_app/data/room/BookmarkDAO.kt
  app/src/main/java/com/example/weather_app/data/room/Repository.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkActivity.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkViewModel.kt
  app/src/main/java/com/example/weather_app/ui/home/HourlyListAdapter.kt
Labels: 🛠 Feat

#18 [FIX] : data class 1개로 수정, 리스트 클릭 시 BookmarkDetailActivity 연결, viewMo…
  app/src/main/java/com/example/weather_app/data/model/BookmarkDataModel.kt
  app/src/main/java/com/example/weather_app/data/model/SearchLocation.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkActivity.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkDetailActivity.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkListAdapter.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkSearchListAdapter.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkViewModel.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/SwipeToDelete.kt
Labels: 🩺 Fix

#19 Fix/search connect api
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkDetailActivity.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkListAdapter.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeActivity.kt
  app/src/main/res/layout/bookmark_rv_item.xml
  app/src/main/res/layout/home_activity.xml
  app/src/main/res/layout/home_daily_item.xml
  app/src/main/res/values/colors.xml
Labels: 📬 API, 🛠 Feat

#20 FIX : viewmodel, getAllData Room 데이터 불러오기 수정
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkViewModel.kt
Labels: 🩺 Fix

#21 Comment : 설명 주석 처리
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkActivity.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkViewModel.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/SwipeToDelete.kt
Labels: 💬 Comment

#23 Fix/local api
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkDetailActivity.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkListAdapter.kt
  app/src/main/java/com/example/weather_app/ui/bookmark/BookmarkViewModel.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeActivity.kt
  app/src/main/java/com/example/weather_app/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/weather_app/util/Utils.kt
Labels: 🩺 Fix
